[package]
name = "atomic_queue"
version = "0.1.0"
authors = ["vvmikheev <mikheev.vv@phystech.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
